### PR TITLE
FDS Validation: Added UL/NIJ Two Story output files

### PR DESCRIPTION
**Pull request by mckinnonm**

### CODE REVIEW

**Comment by rmcdermo** [comment]
Why are you deleting Schoenberg Ekan Layers!?

**Comment by mcgratta** [comment]
Clearly there is something wrong here.

Mark -- just make sure that the UL_NIJ directory in the out repo is the way it should be. Nothing else should be touched. Also, do not commit the _HGL.csv files. These are made using a script. We just need the _devc.csv and _git.txt files. Maybe the _hrr.csv in some cases. HGI.input is needed.

**Comment by mckinnonm** [comment]
I got an error message that my branch had diverged from the central repo and that I had to move or remove several files or they would be overwritten. I may have deleted more files than were indicated. I apologize. I’m still working on understanding this and didn’t realize these commits would change anything other than the UL_NIJ directory.

**Comment by mcgratta** [comment]
Are you working from the command line or using some kind of git graphical tool? Windows or Linux? I always work from the command line and do this
```
git status -uno
```
which tells you what files are modified and what are staged for committing. If I see a bunch of files that I have not touched, I do not commit or push changes to my forked repo on GitHub. When I do finally push what I want to my forked repo, I check one more time that the files I am committing are the files I have changed. Then, and only then, do I formally issue a pull request.

**Comment by mckinnonm** [comment]
Kevin,

Thank you for the advice and your patience. I have been using the command prompt in windows, but I just committed the out files using the online gui and found it to simplify things a little bit. I am going to work toward getting better at this and I’m hoping next time I try to contribute to the FDS project I do not create a host of issues with my commits.

Please let me know if there are any additional issues.

Thanks,

Mark

**Comment by mcgratta** [comment]
You may have read [this](https://github.com/firemodels/fds/wiki/Git-Notes-Getting-Started) already, but you might want to look again. I refer to it all the time. When you make a pull request at GitHub.com, always review the changes before actually issuing the pull request. If something looks fishy, don't issue the pull request and let us know if you're having a problem. I'll check your latest PR.

**Pull request closed without merging**
